// TypeScript bindings for emscripten-generated code.  Automatically generated at compile time.
declare namespace RuntimeExports {
    namespace FS {
        function init(): void;
        let ErrnoError: any;
        function handleError(returnValue: any): any;
        function ensureErrnoError(): void;
        function createDataFile(parent: any, name: any, fileData: any, canRead: any, canWrite: any, canOwn: any): void;
        function createPath(parent: any, path: any, canRead: any, canWrite: any): any;
        function createPreloadedFile(parent: any, name: any, url: any, canRead: any, canWrite: any, onload: any, onerror: any, dontCreateFile: any, canOwn: any, preFinish: any): any;
        function readFile(path: any, opts?: {}): Uint8Array;
        function cwd(): any;
        function analyzePath(path: any): {
            exists: boolean;
            object: {
                contents: any;
            };
        };
        function mkdir(path: any, mode: any): any;
        function mkdirTree(path: any, mode: any): any;
        function rmdir(path: any): any;
        function open(path: any, flags: any, mode?: number): any;
        function create(path: any, mode: any): any;
        function close(stream: any): any;
        function unlink(path: any): any;
        function chdir(path: any): any;
        function read(stream: any, buffer: any, offset: any, length: any, position: any): any;
        function write(stream: any, buffer: any, offset: any, length: any, position: any, canOwn: any): any;
        function allocate(stream: any, offset: any, length: any): any;
        function writeFile(path: any, data: any): any;
        function mmap(stream: any, length: any, offset: any, prot: any, flags: any): {
            ptr: any;
            allocated: boolean;
        };
        function msync(stream: any, bufferPtr: any, offset: any, length: any, mmapFlags: any): any;
        function munmap(addr: any, length: any): any;
        function symlink(target: any, linkpath: any): any;
        function readlink(path: any): any;
        function statBufToObject(statBuf: any): {
            dev: any;
            mode: any;
            nlink: any;
            uid: any;
            gid: any;
            rdev: any;
            size: any;
            blksize: any;
            blocks: any;
            atime: any;
            mtime: any;
            ctime: any;
            ino: any;
        };
        function stat(path: any): any;
        function lstat(path: any): any;
        function chmod(path: any, mode: any): any;
        function lchmod(path: any, mode: any): any;
        function fchmod(fd: any, mode: any): any;
        function utime(path: any, atime: any, mtime: any): any;
        function truncate(path: any, len: any): any;
        function ftruncate(fd: any, len: any): any;
        function findObject(path: any): {
            isFolder: boolean;
            isDevice: boolean;
        };
        function readdir(path: any): any;
        function mount(type: any, opts: any, mountpoint: any): any;
        function unmount(mountpoint: any): any;
        function mknod(path: any, mode: any, dev: any): any;
        function makedev(ma: any, mi: any): number;
        function registerDevice(dev: any, ops: any): void;
        function createDevice(parent: any, name: any, input: any, output: any): any;
        function mkdev(path: any, mode: any, dev: any): any;
        function rename(oldPath: any, newPath: any): any;
        function llseek(stream: any, offset: any, whence: any): any;
    }
    let HEAPF32: any;
    let HEAPF64: any;
    let HEAP_DATA_VIEW: any;
    let HEAP8: any;
    let HEAPU8: any;
    let HEAP16: any;
    let HEAPU16: any;
    let HEAP32: any;
    let HEAPU32: any;
    let HEAP64: any;
    let HEAPU64: any;
    let FS_createPath: any;
    function FS_createDataFile(parent: any, name: any, fileData: any, canRead: any, canWrite: any, canOwn: any): void;
    function FS_createPreloadedFile(parent: any, name: any, url: any, canRead: any, canWrite: any, onload: any, onerror: any, dontCreateFile: any, canOwn: any, preFinish: any): void;
    function FS_unlink(path: any): any;
    let addRunDependency: any;
    let removeRunDependency: any;
}
interface WasmModule {
  ___cxa_allocate_exception(_0: number): number;
  __ZNSt13runtime_errorD1Ev(_0: number): number;
  __Z15initRandomGraphv(_0: number): void;
  __ZN10emscripten3val3setIA9_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZdlPvm(_0: number, _1: number): void;
  __ZN10emscripten3val3setIA10_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setIA11_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __Z11create_nodeP8igraph_siPKcS2_N10emscripten3valE(_0: number, _1: number, _2: number, _3: number, _4: number): void;
  __Z11graph_nodesP8igraph_s(_0: number, _1: number): void;
  __Z11graph_edgesP8igraph_s(_0: number, _1: number): void;
  __Z12cleanupGraphv(): void;
  __Z4testv(): void;
  __Z14what_to_stderrl(_0: number, _1: number): void;
  __Z32create_graph_from_kuzu_to_igraphiN10emscripten3valES0_bS0_(_0: number, _1: number, _2: number, _3: number, _4: number): void;
  __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2B8ne180100ILi0EEEPKc(_0: number, _1: number): number;
  __Znwm(_0: number): number;
  __ZN10emscripten15register_vectorIhEENS_6class_INSt3__26vectorIT_NS2_9allocatorIS4_EEEENS_8internal11NoBaseClassEEEPKc(_0: number): void;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagENS_3valEJEE6invokeEPFS4_vE(_0: number): number;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagEvJEE6invokeEPFvvE(_0: number): void;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagENS_3valEJlEE6invokeEPFS4_lEl(_0: number, _1: number): number;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagENS_3valEJiiEE6invokeEPFS4_iiEii(_0: number, _1: number, _2: number): number;
  __Z25dijkstra_source_to_targetii(_0: number, _1: number, _2: number): void;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagENS_3valEJiEE6invokeEPFS4_iEi(_0: number, _1: number): number;
  __Z22dijkstra_source_to_alli(_0: number, _1: number): void;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagENS_3valEJiiiEE6invokeEPFS4_iiiEiii(_0: number, _1: number, _2: number, _3: number): number;
  __Z20yen_source_to_targetiii(_0: number, _1: number, _2: number, _3: number): void;
  __Z19bf_source_to_targetii(_0: number, _1: number, _2: number): void;
  __Z16bf_source_to_alli(_0: number, _1: number): void;
  __Z3bfsi(_0: number, _1: number): void;
  __Z3dfsi(_0: number, _1: number): void;
  __Z10randomWalkii(_0: number, _1: number, _2: number): void;
  __Z17min_spanning_treev(_0: number): void;
  __Z22betweenness_centralityv(_0: number): void;
  __Z20closeness_centralityv(_0: number): void;
  __Z17degree_centralityv(_0: number): void;
  __Z22eigenvector_centralityv(_0: number): void;
  __Z8strengthv(_0: number): void;
  __Z19harmonic_centralityv(_0: number): void;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagENS_3valEJdEE6invokeEPFS4_dEd(_0: number, _1: number): number;
  __Z8pagerankd(_0: number, _1: number): void;
  __Z7louvaind(_0: number, _1: number): void;
  __Z6leidend(_0: number, _1: number): void;
  __Z11fast_greedyv(_0: number): void;
  __Z17label_propagationv(_0: number): void;
  __Z28local_clustering_coefficientv(_0: number): void;
  __Z6k_corei(_0: number, _1: number): void;
  __Z9trianglesv(_0: number): void;
  __Z29strongly_connected_componentsv(_0: number): void;
  __Z27weakly_connected_componentsv(_0: number): void;
  __Z21vertices_are_adjacentii(_0: number, _1: number, _2: number): void;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagENS_3valEJS4_EE6invokeEPFS4_S4_EPNS_7_EM_VALE(_0: number, _1: number): number;
  __Z18jaccard_similarityN10emscripten3valE(_0: number, _1: number): void;
  __Z16topological_sortv(_0: number): void;
  __Z8diameterv(_0: number): void;
  __Z13eulerian_pathv(_0: number): void;
  __Z16eulerian_circuitv(_0: number): void;
  __Z38missing_edge_prediction_default_valuesv(_0: number): void;
  __Z23missing_edge_predictionii(_0: number, _1: number, _2: number): void;
  __ZN10emscripten8internal7InvokerINS0_3rvp11default_tagEvJiNS_3valES4_bS4_EE6invokeEPFviS4_S4_bS4_EiPNS_7_EM_VALES9_bS9_(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZN10emscripten8internal13getActualTypeINSt3__26vectorIhNS2_9allocatorIhEEEEEEPKvPT_(_0: number): number;
  __ZN10emscripten8internal14raw_destructorINSt3__26vectorIhNS2_9allocatorIhEEEEEEvPT_(_0: number): void;
  __ZN10emscripten8internal7InvokerINS0_3rvp14take_ownershipEPNSt3__26vectorIhNS4_9allocatorIhEEEEJEE6invokeEPFS9_vE(_0: number): number;
  __ZN10emscripten8internal12operator_newINSt3__26vectorIhNS2_9allocatorIhEEEEJEEEPT_DpOT0_(): number;
  __ZN10emscripten8internal13MethodInvokerINS0_3rvp11default_tagEMNSt3__26vectorIhNS4_9allocatorIhEEEEFvRKhEvPS8_JSA_EE6invokeERKSC_SD_h(_0: number, _1: number, _2: number): void;
  __ZN10emscripten8internal13MethodInvokerINS0_3rvp11default_tagEMNSt3__26vectorIhNS4_9allocatorIhEEEEFvmRKhEvPS8_JmSA_EE6invokeERKSC_SD_mh(_0: number, _1: number, _2: number, _3: number): void;
  __ZN10emscripten8internal13MethodInvokerINS0_3rvp11default_tagEMNSt3__26vectorIhNS4_9allocatorIhEEEEKFmvEmPKS8_JEE6invokeERKSA_SC_(_0: number, _1: number): number;
  __ZN10emscripten8internal12VectorAccessINSt3__26vectorIhNS2_9allocatorIhEEEEE3getERKS6_m(_0: number, _1: number, _2: number): void;
  __ZN10emscripten8internal15FunctionInvokerINS0_3rvp11default_tagEPFNSt3__28optionalIhEERKNS4_6vectorIhNS4_9allocatorIhEEEEmES6_SC_JmEE6invokeEPSE_PSA_m(_0: number, _1: number, _2: number): number;
  __ZN10emscripten8internal12VectorAccessINSt3__26vectorIhNS2_9allocatorIhEEEEE3setERS6_mRKh(_0: number, _1: number, _2: number): number;
  __ZN10emscripten8internal15FunctionInvokerINS0_3rvp11default_tagEPFbRNSt3__26vectorIhNS4_9allocatorIhEEEEmRKhEbS9_JmSB_EE6invokeEPSD_PS8_mh(_0: number, _1: number, _2: number, _3: number): number;
  __ZNSt12length_errorD1Ev(_0: number): number;
  __Z21frequenciesToColorMapNSt3__213unordered_mapIiiNS_4hashIiEENS_8equal_toIiEENS_9allocatorINS_4pairIKiiEEEEEERN10emscripten3valE(_0: number, _1: number): void;
  __Z17doublesToColorMapNSt3__213unordered_mapIidNS_4hashIiEENS_8equal_toIiEENS_9allocatorINS_4pairIKidEEEEEERN10emscripten3valE(_0: number, _1: number): void;
  __Z22igraph_check_attributePK8igraph_s(_0: number, _1: number): void;
  __Z16igraph_init_copyP8igraph_sPKS_(_0: number, _1: number): number;
  __Z15igraph_get_namei(_0: number, _1: number): void;
  __Z14igraph_weightsv(): number;
  __Z15scaleCentralitydd(_0: number, _1: number): number;
  __ZN10emscripten3val3setIA8_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __Z23throw_error_if_directedRKNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE(_0: number): void;
  __Z25throw_error_if_undirectedRKNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE(_0: number): void;
  __ZNSt3__26vectorINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEENS4_IS6_EEE21__push_back_slow_pathIS6_EEPS6_OT_(_0: number, _1: number): number;
  __ZN10emscripten3val5arrayINSt3__211__wrap_iterIPKNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEEES0_T_SD_(_0: number, _1: number, _2: number): void;
  __ZNSt3__212__hash_tableINS_17__hash_value_typeIidEENS_22__unordered_map_hasherIiS2_NS_4hashIiEENS_8equal_toIiEELb1EEENS_21__unordered_map_equalIiS2_S7_S5_Lb1EEENS_9allocatorIS2_EEE25__emplace_unique_key_argsIiJRKNS_21piecewise_construct_tENS_5tupleIJRKiEEENSI_IJEEEEEENS_4pairINS_15__hash_iteratorIPNS_11__hash_nodeIS2_PvEEEEbEERKT_DpOT0_(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZNSt3__212__hash_tableINS_17__hash_value_typeIidEENS_22__unordered_map_hasherIiS2_NS_4hashIiEENS_8equal_toIiEELb1EEENS_21__unordered_map_equalIiS2_S7_S5_Lb1EEENS_9allocatorIS2_EEE11__do_rehashILb1EEEvm(_0: number, _1: number): void;
  __ZNSt3__212__hash_tableINS_17__hash_value_typeIidEENS_22__unordered_map_hasherIiS2_NS_4hashIiEENS_8equal_toIiEELb1EEENS_21__unordered_map_equalIiS2_S7_S5_Lb1EEENS_9allocatorIS2_EEE25__emplace_unique_key_argsIiJRKNS_4pairIKidEEEEENSF_INS_15__hash_iteratorIPNS_11__hash_nodeIS2_PvEEEEbEERKT_DpOT0_(_0: number, _1: number, _2: number, _3: number): void;
  __ZN10emscripten3val3setINSt3__212basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEiEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setIA6_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __Z20connected_components22igraph_connectedness_t(_0: number, _1: number): void;
  __ZNSt20bad_array_new_lengthC1Ev(_0: number): number;
  __ZNSt20bad_array_new_lengthD1Ev(_0: number): number;
  __ZN10emscripten3val3setIA7_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setImNSt3__212basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZNSt3__212__hash_tableINS_17__hash_value_typeIiiEENS_22__unordered_map_hasherIiS2_NS_4hashIiEENS_8equal_toIiEELb1EEENS_21__unordered_map_equalIiS2_S7_S5_Lb1EEENS_9allocatorIS2_EEE25__emplace_unique_key_argsIiJRKNS_21piecewise_construct_tENS_5tupleIJRKiEEENSI_IJEEEEEENS_4pairINS_15__hash_iteratorIPNS_11__hash_nodeIS2_PvEEEEbEERKT_DpOT0_(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZNSt3__212__hash_tableINS_17__hash_value_typeIiiEENS_22__unordered_map_hasherIiS2_NS_4hashIiEENS_8equal_toIiEELb1EEENS_21__unordered_map_equalIiS2_S7_S5_Lb1EEENS_9allocatorIS2_EEE11__do_rehashILb1EEEvm(_0: number, _1: number): void;
  __ZNSt3__212__hash_tableINS_17__hash_value_typeIiiEENS_22__unordered_map_hasherIiS2_NS_4hashIiEENS_8equal_toIiEELb1EEENS_21__unordered_map_equalIiS2_S7_S5_Lb1EEENS_9allocatorIS2_EEE25__emplace_unique_key_argsIiJRKNS_4pairIKiiEEEEENSF_INS_15__hash_iteratorIPNS_11__hash_nodeIS2_PvEEEEbEERKT_DpOT0_(_0: number, _1: number, _2: number, _3: number): void;
  __ZN10emscripten3val3setINSt3__212basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEdEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setIA5_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setIA3_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setIA4_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setIA12_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setIiNSt3__212basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZNSt3__212__hash_tableIiNS_4hashIiEENS_8equal_toIiEENS_9allocatorIiEEE25__emplace_unique_key_argsIiJRKiEEENS_4pairINS_15__hash_iteratorIPNS_11__hash_nodeIiPvEEEEbEERKT_DpOT0_(_0: number, _1: number, _2: number, _3: number): void;
  __ZN10emscripten3val3setIA17_cNSt3__212basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __ZNSt3__212__hash_tableIiNS_4hashIiEENS_8equal_toIiEENS_9allocatorIiEEE11__do_rehashILb1EEEvm(_0: number, _1: number): void;
  __Z24vertex_attributes_objectPK8igraph_si(_0: number, _1: number, _2: number): void;
  __ZN10emscripten3val3setIPKcNSt3__212basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEEEvRKT_RKT0_(_0: number, _1: number, _2: number): void;
  __Z22edge_attributes_objectPK8igraph_si(_0: number, _1: number, _2: number): void;
  __ZNSt9exceptionD2Ev(_0: number): number;
  __Znam(_0: number): number;
  __ZdaPv(_0: number): void;
  __ZNSt16invalid_argumentD1Ev(_0: number): number;
  __ZdlPv(_0: number): void;
  _setTempRet0(_0: number): void;
  _getTempRet0(): number;
  __ZNSt9bad_allocC1Ev(_0: number): number;
  __ZNSt9bad_allocD1Ev(_0: number): number;
  __ZNSt12out_of_rangeD1Ev(_0: number): number;
  ___cxa_pure_virtual(): void;
  __ZN4pugi10xml_writerD2Ev(_0: number): number;
  __ZN4pugi10xml_writerD0Ev(_0: number): void;
  __ZN4pugi15xml_writer_fileC2EPv(_0: number, _1: number): number;
  __ZN4pugi10xml_writerC2Ev(_0: number): number;
  __ZN4pugi15xml_writer_file5writeEPKvm(_0: number, _1: number, _2: number): void;
  __ZN4pugi17xml_writer_streamC2ERNSt3__213basic_ostreamIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi17xml_writer_streamC2ERNSt3__213basic_ostreamIwNS1_11char_traitsIwEEEE(_0: number, _1: number): number;
  __ZN4pugi17xml_writer_stream5writeEPKvm(_0: number, _1: number, _2: number): void;
  __ZN4pugi15xml_tree_walkerC2Ev(_0: number): number;
  __ZN4pugi15xml_tree_walkerD2Ev(_0: number): number;
  __ZN4pugi15xml_tree_walkerD0Ev(_0: number): void;
  __ZNK4pugi15xml_tree_walker5depthEv(_0: number): number;
  __ZN4pugi15xml_tree_walker5beginERNS_8xml_nodeE(_0: number, _1: number): number;
  __ZN4pugi15xml_tree_walker3endERNS_8xml_nodeE(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeC2Ev(_0: number): number;
  __ZN4pugi13xml_attributeC2EPNS_20xml_attribute_structE(_0: number, _1: number): number;
  __ZNK4pugi13xml_attributecvPFvPPPS0_EEv(_0: number): number;
  __ZNK4pugi13xml_attributentEv(_0: number): number;
  __ZNK4pugi13xml_attributeeqERKS0_(_0: number, _1: number): number;
  __ZNK4pugi13xml_attributeneERKS0_(_0: number, _1: number): number;
  __ZNK4pugi13xml_attributeltERKS0_(_0: number, _1: number): number;
  __ZNK4pugi13xml_attributegtERKS0_(_0: number, _1: number): number;
  __ZNK4pugi13xml_attributeleERKS0_(_0: number, _1: number): number;
  __ZNK4pugi13xml_attributegeERKS0_(_0: number, _1: number): number;
  __ZNK4pugi13xml_attribute14next_attributeEv(_0: number): number;
  __ZN4pugi13xml_attributeC1Ev(_0: number): number;
  __ZN4pugi13xml_attributeC1EPNS_20xml_attribute_structE(_0: number, _1: number): number;
  __ZNK4pugi13xml_attribute18previous_attributeEv(_0: number): number;
  __ZNK4pugi13xml_attribute9as_stringEPKc(_0: number, _1: number): number;
  __ZNK4pugi13xml_attribute6as_intEi(_0: number, _1: number): number;
  __ZNK4pugi13xml_attribute7as_uintEj(_0: number, _1: number): number;
  __ZNK4pugi13xml_attribute9as_doubleEd(_0: number, _1: number): number;
  __ZNK4pugi13xml_attribute8as_floatEf(_0: number, _1: number): number;
  __ZNK4pugi13xml_attribute7as_boolEb(_0: number, _1: number): number;
  __ZNK4pugi13xml_attribute8as_llongEx(_0: number, _1: number, _2: number): number;
  __ZNK4pugi13xml_attribute9as_ullongEy(_0: number, _1: number, _2: number): number;
  __ZNK4pugi13xml_attribute5emptyEv(_0: number): number;
  __ZNK4pugi13xml_attribute4nameEv(_0: number): number;
  __ZNK4pugi13xml_attribute5valueEv(_0: number): number;
  __ZNK4pugi13xml_attribute10hash_valueEv(_0: number): number;
  __ZNK4pugi13xml_attribute15internal_objectEv(_0: number): number;
  __ZN4pugi13xml_attributeaSEPKc(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEPKc(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSEi(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEi(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSEj(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEj(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSEl(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEl(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSEm(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEm(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSEd(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEd(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSEf(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEf(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSEb(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEb(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi13xml_attributeaSEx(_0: number, _1: number, _2: number): number;
  __ZN4pugi13xml_attribute9set_valueEx(_0: number, _1: number, _2: number): number;
  __ZN4pugi13xml_attributeaSEy(_0: number, _1: number, _2: number): number;
  __ZN4pugi13xml_attribute9set_valueEy(_0: number, _1: number, _2: number): number;
  __ZN4pugi13xml_attribute8set_nameEPKc(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute8set_nameEPKcm(_0: number, _1: number, _2: number): number;
  __ZN4pugi13xml_attribute8set_nameENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi13xml_attribute9set_valueEPKcm(_0: number, _1: number, _2: number): number;
  __ZN4pugi13xml_attribute9set_valueEdi(_0: number, _1: number, _2: number): number;
  __ZN4pugi13xml_attribute9set_valueEfi(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_nodeC2Ev(_0: number): number;
  __ZN4pugi8xml_nodeC2EPNS_15xml_node_structE(_0: number, _1: number): number;
  __ZNK4pugi8xml_nodecvPFvPPPS0_EEv(_0: number): number;
  __ZNK4pugi8xml_nodentEv(_0: number): number;
  __ZNK4pugi8xml_node5beginEv(_0: number, _1: number): void;
  __ZN4pugi17xml_node_iteratorC1EPNS_15xml_node_structES2_(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_node3endEv(_0: number, _1: number): void;
  __ZNK4pugi8xml_node16attributes_beginEv(_0: number, _1: number): void;
  __ZN4pugi22xml_attribute_iteratorC1EPNS_20xml_attribute_structEPNS_15xml_node_structE(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_node14attributes_endEv(_0: number, _1: number): void;
  __ZNK4pugi8xml_node8childrenEv(_0: number, _1: number): void;
  __ZN4pugi16xml_object_rangeINS_17xml_node_iteratorEEC2ES1_S1_(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_node8childrenEPKc(_0: number, _1: number, _2: number): void;
  __ZNK4pugi8xml_node5childEPKc(_0: number, _1: number): number;
  __ZN4pugi23xml_named_node_iteratorC1EPNS_15xml_node_structES2_PKc(_0: number, _1: number, _2: number, _3: number): number;
  __ZN4pugi16xml_object_rangeINS_23xml_named_node_iteratorEEC2ES1_S1_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_nodeC1Ev(_0: number): number;
  __ZN4pugi8xml_nodeC1EPNS_15xml_node_structE(_0: number, _1: number): number;
  __ZNK4pugi8xml_node10attributesEv(_0: number, _1: number): void;
  __ZN4pugi16xml_object_rangeINS_22xml_attribute_iteratorEEC2ES1_S1_(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_nodeeqERKS0_(_0: number, _1: number): number;
  __ZNK4pugi8xml_nodeneERKS0_(_0: number, _1: number): number;
  __ZNK4pugi8xml_nodeltERKS0_(_0: number, _1: number): number;
  __ZNK4pugi8xml_nodegtERKS0_(_0: number, _1: number): number;
  __ZNK4pugi8xml_nodeleERKS0_(_0: number, _1: number): number;
  __ZNK4pugi8xml_nodegeERKS0_(_0: number, _1: number): number;
  __ZNK4pugi8xml_node5emptyEv(_0: number): number;
  __ZNK4pugi8xml_node4nameEv(_0: number): number;
  __ZNK4pugi8xml_node4typeEv(_0: number): number;
  __ZNK4pugi8xml_node5valueEv(_0: number): number;
  __ZNK4pugi8xml_node9attributeEPKc(_0: number, _1: number): number;
  __ZNK4pugi8xml_node12next_siblingEPKc(_0: number, _1: number): number;
  __ZNK4pugi8xml_node12next_siblingEv(_0: number): number;
  __ZNK4pugi8xml_node16previous_siblingEPKc(_0: number, _1: number): number;
  __ZNK4pugi8xml_node5childENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZNK4pugi8xml_node9attributeENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZNK4pugi8xml_node12next_siblingENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZNK4pugi8xml_node16previous_siblingENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZNK4pugi8xml_node9attributeEPKcRNS_13xml_attributeE(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_node9attributeENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEERNS_13xml_attributeE(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_node16previous_siblingEv(_0: number): number;
  __ZNK4pugi8xml_node6parentEv(_0: number): number;
  __ZNK4pugi8xml_node4rootEv(_0: number): number;
  __ZNK4pugi8xml_node4textEv(_0: number): number;
  __ZN4pugi8xml_textC1EPNS_15xml_node_structE(_0: number, _1: number): number;
  __ZNK4pugi8xml_node11child_valueEv(_0: number): number;
  __ZNK4pugi8xml_node11child_valueEPKc(_0: number, _1: number): number;
  __ZNK4pugi8xml_node15first_attributeEv(_0: number): number;
  __ZNK4pugi8xml_node14last_attributeEv(_0: number): number;
  __ZNK4pugi8xml_node11first_childEv(_0: number): number;
  __ZNK4pugi8xml_node10last_childEv(_0: number): number;
  __ZN4pugi8xml_node8set_nameEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node8set_nameEPKcm(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node8set_nameENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node9set_valueEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node9set_valueEPKcm(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node9set_valueENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node16append_attributeEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node17prepend_attributeEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node22insert_attribute_afterEPKcRKNS_13xml_attributeE(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node23insert_attribute_beforeEPKcRKNS_13xml_attributeE(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node16append_attributeENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node17prepend_attributeENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node22insert_attribute_afterENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEERKNS_13xml_attributeE(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node23insert_attribute_beforeENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEERKNS_13xml_attributeE(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node16ensure_attributeEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node16ensure_attributeENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node11append_copyERKNS_13xml_attributeE(_0: number, _1: number): number;
  __ZN4pugi8xml_node12prepend_copyERKNS_13xml_attributeE(_0: number, _1: number): number;
  __ZN4pugi8xml_node17insert_copy_afterERKNS_13xml_attributeES3_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node18insert_copy_beforeERKNS_13xml_attributeES3_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node12append_childENS_13xml_node_typeE(_0: number, _1: number): number;
  __ZN4pugi8xml_node13prepend_childENS_13xml_node_typeE(_0: number, _1: number): number;
  __ZN4pugi8xml_node19insert_child_beforeENS_13xml_node_typeERKS0_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node18insert_child_afterENS_13xml_node_typeERKS0_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node12append_childEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node13prepend_childEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node18insert_child_afterEPKcRKS0_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node19insert_child_beforeEPKcRKS0_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node12append_childENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node13prepend_childENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node18insert_child_afterENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEERKS0_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node19insert_child_beforeENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEERKS0_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node12ensure_childEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node12ensure_childENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node11append_copyERKS0_(_0: number, _1: number): number;
  __ZN4pugi8xml_node12prepend_copyERKS0_(_0: number, _1: number): number;
  __ZN4pugi8xml_node17insert_copy_afterERKS0_S2_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node18insert_copy_beforeERKS0_S2_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node11append_moveERKS0_(_0: number, _1: number): number;
  __ZN4pugi8xml_node12prepend_moveERKS0_(_0: number, _1: number): number;
  __ZN4pugi8xml_node17insert_move_afterERKS0_S2_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node18insert_move_beforeERKS0_S2_(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node16remove_attributeEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node16remove_attributeERKNS_13xml_attributeE(_0: number, _1: number): number;
  __ZN4pugi8xml_node16remove_attributeENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node17remove_attributesEv(_0: number): number;
  __ZN4pugi8xml_node12remove_childEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_node12remove_childERKS0_(_0: number, _1: number): number;
  __ZN4pugi8xml_node12remove_childENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_node15remove_childrenEv(_0: number): number;
  __ZN4pugi8xml_node13append_bufferEPKvmjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZN4pugi16xml_parse_resultC1Ev(_0: number): number;
  __ZNK4pugi8xml_node23find_child_by_attributeEPKcS2_S2_(_0: number, _1: number, _2: number, _3: number): number;
  __ZNK4pugi8xml_node23find_child_by_attributeEPKcS2_(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_node4pathEc(_0: number, _1: number, _2: number): void;
  __ZNSt3__217__compressed_pairINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE5__repES5_EC2B8ne180100INS_16__value_init_tagENS_18__default_init_tagEEEOT_OT0_(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_node21first_element_by_pathEPKcc(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_node8traverseERNS_15xml_tree_walkerE(_0: number, _1: number): number;
  __ZNK4pugi8xml_node10hash_valueEv(_0: number): number;
  __ZNK4pugi8xml_node15internal_objectEv(_0: number): number;
  __ZNK4pugi8xml_node5printERNS_10xml_writerEPKcjNS_12xml_encodingEj(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZNK4pugi8xml_node5printERNSt3__213basic_ostreamIcNS1_11char_traitsIcEEEEPKcjNS_12xml_encodingEj(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZN4pugi17xml_writer_streamC1ERNSt3__213basic_ostreamIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi17xml_writer_streamD2Ev(_0: number): number;
  __ZNK4pugi8xml_node5printERNSt3__213basic_ostreamIwNS1_11char_traitsIwEEEEPKcjj(_0: number, _1: number, _2: number, _3: number, _4: number): void;
  __ZN4pugi17xml_writer_streamC1ERNSt3__213basic_ostreamIwNS1_11char_traitsIwEEEE(_0: number, _1: number): number;
  __ZNK4pugi8xml_node12offset_debugEv(_0: number): number;
  __ZN4pugi8xml_textC2EPNS_15xml_node_structE(_0: number, _1: number): number;
  __ZNK4pugi8xml_text5_dataEv(_0: number): number;
  __ZN4pugi8xml_text9_data_newEv(_0: number): number;
  __ZN4pugi8xml_textC2Ev(_0: number): number;
  __ZNK4pugi8xml_textcvPFvPPPS0_EEv(_0: number): number;
  __ZNK4pugi8xml_textntEv(_0: number): number;
  __ZNK4pugi8xml_text5emptyEv(_0: number): number;
  __ZNK4pugi8xml_text3getEv(_0: number): number;
  __ZNK4pugi8xml_text9as_stringEPKc(_0: number, _1: number): number;
  __ZNK4pugi8xml_text6as_intEi(_0: number, _1: number): number;
  __ZNK4pugi8xml_text7as_uintEj(_0: number, _1: number): number;
  __ZNK4pugi8xml_text9as_doubleEd(_0: number, _1: number): number;
  __ZNK4pugi8xml_text8as_floatEf(_0: number, _1: number): number;
  __ZNK4pugi8xml_text7as_boolEb(_0: number, _1: number): number;
  __ZNK4pugi8xml_text8as_llongEx(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_text9as_ullongEy(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_text3setEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEPKcm(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_text3setENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEi(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEj(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEl(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEm(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEf(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEfi(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_text3setEd(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEdi(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_text3setEb(_0: number, _1: number): number;
  __ZN4pugi8xml_text3setEx(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_text3setEy(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_textaSEPKc(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSEi(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSEj(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSEl(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSEm(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSEd(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSEf(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSEb(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZN4pugi8xml_textaSEx(_0: number, _1: number, _2: number): number;
  __ZN4pugi8xml_textaSEy(_0: number, _1: number, _2: number): number;
  __ZNK4pugi8xml_text4dataEv(_0: number): number;
  __ZN4pugi17xml_node_iteratorC2Ev(_0: number): number;
  __ZN4pugi17xml_node_iteratorC2ERKNS_8xml_nodeE(_0: number, _1: number): number;
  __ZN4pugi17xml_node_iteratorC2EPNS_15xml_node_structES2_(_0: number, _1: number, _2: number): number;
  __ZNK4pugi17xml_node_iteratoreqERKS0_(_0: number, _1: number): number;
  __ZNK4pugi17xml_node_iteratorneERKS0_(_0: number, _1: number): number;
  __ZNK4pugi17xml_node_iteratordeEv(_0: number): number;
  __ZNK4pugi17xml_node_iteratorptEv(_0: number): number;
  __ZN4pugi17xml_node_iteratorppEv(_0: number): number;
  __ZN4pugi17xml_node_iteratorppEi(_0: number, _1: number, _2: number): void;
  __ZN4pugi17xml_node_iteratormmEv(_0: number): number;
  __ZN4pugi17xml_node_iteratormmEi(_0: number, _1: number, _2: number): void;
  __ZN4pugi22xml_attribute_iteratorC2Ev(_0: number): number;
  __ZN4pugi22xml_attribute_iteratorC2ERKNS_13xml_attributeERKNS_8xml_nodeE(_0: number, _1: number, _2: number): number;
  __ZN4pugi22xml_attribute_iteratorC2EPNS_20xml_attribute_structEPNS_15xml_node_structE(_0: number, _1: number, _2: number): number;
  __ZNK4pugi22xml_attribute_iteratoreqERKS0_(_0: number, _1: number): number;
  __ZNK4pugi22xml_attribute_iteratorneERKS0_(_0: number, _1: number): number;
  __ZNK4pugi22xml_attribute_iteratordeEv(_0: number): number;
  __ZNK4pugi22xml_attribute_iteratorptEv(_0: number): number;
  __ZN4pugi22xml_attribute_iteratorppEv(_0: number): number;
  __ZN4pugi22xml_attribute_iteratorppEi(_0: number, _1: number, _2: number): void;
  __ZN4pugi22xml_attribute_iteratormmEv(_0: number): number;
  __ZN4pugi22xml_attribute_iteratormmEi(_0: number, _1: number, _2: number): void;
  __ZN4pugi23xml_named_node_iteratorC2Ev(_0: number): number;
  __ZN4pugi23xml_named_node_iteratorC2ERKNS_8xml_nodeEPKc(_0: number, _1: number, _2: number): number;
  __ZN4pugi23xml_named_node_iteratorC2EPNS_15xml_node_structES2_PKc(_0: number, _1: number, _2: number, _3: number): number;
  __ZNK4pugi23xml_named_node_iteratoreqERKS0_(_0: number, _1: number): number;
  __ZNK4pugi23xml_named_node_iteratorneERKS0_(_0: number, _1: number): number;
  __ZNK4pugi23xml_named_node_iteratordeEv(_0: number): number;
  __ZNK4pugi23xml_named_node_iteratorptEv(_0: number): number;
  __ZN4pugi23xml_named_node_iteratorppEv(_0: number): number;
  __ZN4pugi23xml_named_node_iteratorppEi(_0: number, _1: number, _2: number): void;
  __ZN4pugi23xml_named_node_iteratormmEv(_0: number): number;
  __ZN4pugi23xml_named_node_iteratormmEi(_0: number, _1: number, _2: number): void;
  __ZN4pugi16xml_parse_resultC2Ev(_0: number): number;
  __ZNK4pugi16xml_parse_resultcvbEv(_0: number): number;
  __ZNK4pugi16xml_parse_result11descriptionEv(_0: number): number;
  __ZN4pugi12xml_documentC2Ev(_0: number): number;
  __ZN4pugi12xml_document7_createEv(_0: number): void;
  __ZN4pugi12xml_documentD2Ev(_0: number): number;
  __ZN4pugi12xml_document8_destroyEv(_0: number): void;
  __ZN4pugi12xml_documentC2EOS0_(_0: number, _1: number): number;
  __ZN4pugi12xml_document5_moveERS0_(_0: number, _1: number): void;
  __ZN4pugi12xml_documentaSEOS0_(_0: number, _1: number): number;
  __ZN4pugi12xml_document5resetEv(_0: number): void;
  __ZN4pugi12xml_document5resetERKS0_(_0: number, _1: number): void;
  __ZN4pugi12xml_document4loadERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEEjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number): void;
  __ZN4pugi12xml_document4loadERNSt3__213basic_istreamIwNS1_11char_traitsIwEEEEj(_0: number, _1: number, _2: number, _3: number): void;
  __ZN4pugi12xml_document11load_stringEPKcj(_0: number, _1: number, _2: number, _3: number): void;
  __ZN4pugi12xml_document11load_bufferEPKvmjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZN4pugi12xml_document4loadEPKcj(_0: number, _1: number, _2: number, _3: number): void;
  __ZN4pugi12xml_document9load_fileEPKcjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number): void;
  __ZN4pugi12xml_document9load_fileEPKwjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number): void;
  __ZN4pugi12xml_document19load_buffer_inplaceEPvmjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZN4pugi12xml_document23load_buffer_inplace_ownEPvmjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZNK4pugi12xml_document4saveERNS_10xml_writerEPKcjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number): void;
  __ZNK4pugi12xml_document4saveERNSt3__213basic_ostreamIcNS1_11char_traitsIcEEEEPKcjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number): void;
  __ZNK4pugi12xml_document4saveERNSt3__213basic_ostreamIwNS1_11char_traitsIwEEEEPKcj(_0: number, _1: number, _2: number, _3: number): void;
  __ZNK4pugi12xml_document9save_fileEPKcS2_jNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN4pugi15xml_writer_fileC1EPv(_0: number, _1: number): number;
  __ZN4pugi15xml_writer_fileD2Ev(_0: number): number;
  __ZNK4pugi12xml_document9save_fileEPKwPKcjNS_12xml_encodingE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZNK4pugi12xml_document16document_elementEv(_0: number): number;
  __ZN4pugi7as_utf8EPKw(_0: number, _1: number): void;
  __ZN4pugi7as_utf8ERKNSt3__212basic_stringIwNS0_11char_traitsIwEENS0_9allocatorIwEEEE(_0: number, _1: number): void;
  __ZN4pugi7as_wideEPKc(_0: number, _1: number): void;
  __ZN4pugi7as_wideERKNSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE(_0: number, _1: number): void;
  __ZN4pugi31set_memory_management_functionsEPFPvmEPFvS0_E(_0: number, _1: number): void;
  __ZN4pugi30get_memory_allocation_functionEv(): number;
  __ZN4pugi32get_memory_deallocation_functionEv(): number;
  __ZN4pugi15xpath_exceptionC2ERKNS_18xpath_parse_resultE(_0: number, _1: number): number;
  __ZNK4pugi15xpath_exception4whatEv(_0: number): number;
  __ZNK4pugi15xpath_exception6resultEv(_0: number): number;
  __ZN4pugi10xpath_nodeC2Ev(_0: number): number;
  __ZN4pugi10xpath_nodeC2ERKNS_8xml_nodeE(_0: number, _1: number): number;
  __ZN4pugi10xpath_nodeC2ERKNS_13xml_attributeERKNS_8xml_nodeE(_0: number, _1: number, _2: number): number;
  __ZNK4pugi10xpath_node4nodeEv(_0: number): number;
  __ZNK4pugi10xpath_node9attributeEv(_0: number): number;
  __ZNK4pugi10xpath_node6parentEv(_0: number): number;
  __ZNK4pugi10xpath_nodecvPFvPPPS0_EEv(_0: number): number;
  __ZNK4pugi10xpath_nodentEv(_0: number): number;
  __ZNK4pugi10xpath_nodeeqERKS0_(_0: number, _1: number): number;
  __ZNK4pugi10xpath_nodeneERKS0_(_0: number, _1: number): number;
  __ZN4pugi14xpath_node_set7_assignEPKNS_10xpath_nodeES3_NS0_6type_tE(_0: number, _1: number, _2: number, _3: number): void;
  __ZN4pugi14xpath_node_set5_moveERS0_(_0: number, _1: number): void;
  __ZN4pugi14xpath_node_setC2Ev(_0: number): number;
  __ZN4pugi10xpath_nodeC1Ev(_0: number): number;
  __ZN4pugi14xpath_node_setC2EPKNS_10xpath_nodeES3_NS0_6type_tE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN4pugi14xpath_node_setD2Ev(_0: number): number;
  __ZN4pugi14xpath_node_setC2ERKS0_(_0: number, _1: number): number;
  __ZN4pugi14xpath_node_setaSERKS0_(_0: number, _1: number): number;
  __ZN4pugi14xpath_node_setC2EOS0_(_0: number, _1: number): number;
  __ZN4pugi14xpath_node_setaSEOS0_(_0: number, _1: number): number;
  __ZNK4pugi14xpath_node_set4typeEv(_0: number): number;
  __ZNK4pugi14xpath_node_set4sizeEv(_0: number): number;
  __ZNK4pugi14xpath_node_set5emptyEv(_0: number): number;
  __ZNK4pugi14xpath_node_setixEm(_0: number, _1: number): number;
  __ZNK4pugi14xpath_node_set5beginEv(_0: number): number;
  __ZNK4pugi14xpath_node_set3endEv(_0: number): number;
  __ZN4pugi14xpath_node_set4sortEb(_0: number, _1: number): void;
  __ZNK4pugi14xpath_node_set5firstEv(_0: number, _1: number): void;
  __ZN4pugi18xpath_parse_resultC2Ev(_0: number): number;
  __ZNK4pugi18xpath_parse_resultcvbEv(_0: number): number;
  __ZNK4pugi18xpath_parse_result11descriptionEv(_0: number): number;
  __ZN4pugi14xpath_variableC2ENS_16xpath_value_typeE(_0: number, _1: number): number;
  __ZNK4pugi14xpath_variable4nameEv(_0: number): number;
  __ZNK4pugi14xpath_variable4typeEv(_0: number): number;
  __ZNK4pugi14xpath_variable11get_booleanEv(_0: number): number;
  __ZNK4pugi14xpath_variable10get_numberEv(_0: number): number;
  __ZNK4pugi14xpath_variable10get_stringEv(_0: number): number;
  __ZNK4pugi14xpath_variable12get_node_setEv(_0: number): number;
  __ZN4pugi14xpath_node_setC1Ev(_0: number): number;
  __ZN4pugi14xpath_node_setD1Ev(_0: number): number;
  __ZN4pugi14xpath_variable3setEb(_0: number, _1: number): number;
  __ZN4pugi14xpath_variable3setEd(_0: number, _1: number): number;
  __ZN4pugi14xpath_variable3setEPKc(_0: number, _1: number): number;
  __ZN4pugi14xpath_variable3setERKNS_14xpath_node_setE(_0: number, _1: number): number;
  __ZN4pugi18xpath_variable_setC2Ev(_0: number): number;
  __ZN4pugi18xpath_variable_setD2Ev(_0: number): number;
  __ZN4pugi18xpath_variable_set8_destroyEPNS_14xpath_variableE(_0: number): void;
  __ZN4pugi18xpath_variable_setC2ERKS0_(_0: number, _1: number): number;
  __ZN4pugi18xpath_variable_set7_assignERKS0_(_0: number, _1: number): void;
  __ZN4pugi18xpath_variable_setC1Ev(_0: number): number;
  __ZN4pugi18xpath_variable_set6_cloneEPNS_14xpath_variableEPS2_(_0: number, _1: number): number;
  __ZN4pugi18xpath_variable_set5_swapERS0_(_0: number, _1: number): void;
  __ZN4pugi18xpath_variable_setD1Ev(_0: number): number;
  __ZN4pugi18xpath_variable_setaSERKS0_(_0: number, _1: number): number;
  __ZN4pugi18xpath_variable_setC2EOS0_(_0: number, _1: number): number;
  __ZN4pugi18xpath_variable_setaSEOS0_(_0: number, _1: number): number;
  __ZNK4pugi18xpath_variable_set5_findEPKc(_0: number, _1: number): number;
  __ZN4pugi18xpath_variable_set3addEPKcNS_16xpath_value_typeE(_0: number, _1: number, _2: number): number;
  __ZN4pugi18xpath_variable_set3setEPKcb(_0: number, _1: number, _2: number): number;
  __ZN4pugi18xpath_variable_set3setEPKcd(_0: number, _1: number, _2: number): number;
  __ZN4pugi18xpath_variable_set3setEPKcS2_(_0: number, _1: number, _2: number): number;
  __ZN4pugi18xpath_variable_set3setEPKcRKNS_14xpath_node_setE(_0: number, _1: number, _2: number): number;
  __ZN4pugi18xpath_variable_set3getEPKc(_0: number, _1: number): number;
  __ZNK4pugi18xpath_variable_set3getEPKc(_0: number, _1: number): number;
  __ZN4pugi11xpath_queryC2EPKcPNS_18xpath_variable_setE(_0: number, _1: number, _2: number): number;
  __ZN4pugi18xpath_parse_resultC1Ev(_0: number): number;
  __ZN4pugi15xpath_exceptionC1ERKNS_18xpath_parse_resultE(_0: number, _1: number): number;
  __ZN4pugi15xpath_exceptionD2Ev(_0: number): number;
  __ZN4pugi11xpath_queryC2Ev(_0: number): number;
  __ZN4pugi11xpath_queryD2Ev(_0: number): number;
  __ZN4pugi11xpath_queryC2EOS0_(_0: number, _1: number): number;
  __ZN4pugi11xpath_queryaSEOS0_(_0: number, _1: number): number;
  __ZNK4pugi11xpath_query11return_typeEv(_0: number): number;
  __ZNK4pugi11xpath_query16evaluate_booleanERKNS_10xpath_nodeE(_0: number, _1: number): number;
  __ZNK4pugi11xpath_query15evaluate_numberERKNS_10xpath_nodeE(_0: number, _1: number): number;
  __ZNK4pugi11xpath_query15evaluate_stringERKNS_10xpath_nodeE(_0: number, _1: number, _2: number): void;
  __ZNSt3__217__compressed_pairINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE5__repES5_EC2B8ne180100INS_18__default_init_tagESA_EEOT_OT0_(_0: number, _1: number, _2: number): number;
  __ZNK4pugi11xpath_query15evaluate_stringEPcmRKNS_10xpath_nodeE(_0: number, _1: number, _2: number, _3: number): number;
  __ZNK4pugi11xpath_query17evaluate_node_setERKNS_10xpath_nodeE(_0: number, _1: number, _2: number): void;
  __ZN4pugi14xpath_node_setC1EPKNS_10xpath_nodeES3_NS0_6type_tE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN4pugi10xpath_nodeC1ERKNS_8xml_nodeE(_0: number, _1: number): number;
  __ZN4pugi10xpath_nodeC1ERKNS_13xml_attributeERKNS_8xml_nodeE(_0: number, _1: number, _2: number): number;
  __ZNK4pugi11xpath_query13evaluate_nodeERKNS_10xpath_nodeE(_0: number, _1: number, _2: number): void;
  __ZNK4pugi11xpath_query6resultEv(_0: number): number;
  __ZNK4pugi11xpath_querycvPFvPPPS0_EEv(_0: number): number;
  __ZNK4pugi11xpath_queryntEv(_0: number): number;
  __ZNK4pugi8xml_node11select_nodeEPKcPNS_18xpath_variable_setE(_0: number, _1: number, _2: number, _3: number): void;
  __ZN4pugi11xpath_queryC1EPKcPNS_18xpath_variable_setE(_0: number, _1: number, _2: number): number;
  __ZN4pugi11xpath_queryD1Ev(_0: number): number;
  __ZNK4pugi8xml_node11select_nodeERKNS_11xpath_queryE(_0: number, _1: number, _2: number): void;
  __ZNK4pugi8xml_node12select_nodesEPKcPNS_18xpath_variable_setE(_0: number, _1: number, _2: number, _3: number): void;
  __ZNK4pugi8xml_node12select_nodesERKNS_11xpath_queryE(_0: number, _1: number, _2: number): void;
  __ZNK4pugi8xml_node18select_single_nodeEPKcPNS_18xpath_variable_setE(_0: number, _1: number, _2: number, _3: number): void;
  __ZNK4pugi8xml_node18select_single_nodeERKNS_11xpath_queryE(_0: number, _1: number, _2: number): void;
  __ZN4pugi15xml_writer_fileD0Ev(_0: number): void;
  __ZN4pugi17xml_writer_streamD0Ev(_0: number): void;
  __ZN4pugi15xpath_exceptionD0Ev(_0: number): void;
  __ZNSt3__217__compressed_pairINS_12basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEE5__repES5_EC2B8ne180100INS_16__value_init_tagENS_18__default_init_tagEEEOT_OT0_(_0: number, _1: number, _2: number): number;
  __ZN4pugi15xml_tree_walkerD1Ev(_0: number): number;
  __ZN4pugi10xml_writerD1Ev(_0: number): number;
  __ZN4pugi8xml_textC1Ev(_0: number): number;
  __ZN4pugi17xml_node_iteratorC1Ev(_0: number): number;
  __ZN4pugi17xml_node_iteratorC1ERKNS_8xml_nodeE(_0: number, _1: number): number;
  __ZN4pugi22xml_attribute_iteratorC1Ev(_0: number): number;
  __ZN4pugi22xml_attribute_iteratorC1ERKNS_13xml_attributeERKNS_8xml_nodeE(_0: number, _1: number, _2: number): number;
  __ZN4pugi23xml_named_node_iteratorC1Ev(_0: number): number;
  __ZN4pugi23xml_named_node_iteratorC1ERKNS_8xml_nodeEPKc(_0: number, _1: number, _2: number): number;
  __ZN4pugi12xml_documentC1Ev(_0: number): number;
  __ZN4pugi12xml_documentD1Ev(_0: number): number;
  __ZN4pugi12xml_documentC1EOS0_(_0: number, _1: number): number;
  __ZN4pugi14xpath_node_setC1ERKS0_(_0: number, _1: number): number;
  __ZN4pugi14xpath_node_setC1EOS0_(_0: number, _1: number): number;
  __ZN4pugi14xpath_variableC1ENS_16xpath_value_typeE(_0: number, _1: number): number;
  __ZN4pugi18xpath_variable_setC1ERKS0_(_0: number, _1: number): number;
  __ZN4pugi18xpath_variable_setC1EOS0_(_0: number, _1: number): number;
  __ZN4pugi11xpath_queryC1Ev(_0: number): number;
  __ZN4pugi11xpath_queryC1EOS0_(_0: number, _1: number): number;
  _emscripten_stack_get_base(): number;
  _emscripten_stack_get_end(): number;
  ___emutls_get_address(_0: number): number;
  _emscripten_stack_init(): void;
  _emscripten_stack_set_limits(_0: number, _1: number): void;
  _emscripten_stack_get_free(): number;
  __ZNSt8bad_castD2Ev(_0: number): number;
  __ZnamSt11align_val_t(_0: number, _1: number): number;
  __ZdaPvSt11align_val_t(_0: number, _1: number): void;
  __ZnwmSt11align_val_t(_0: number, _1: number): number;
  __ZdlPvmSt11align_val_t(_0: number, _1: number, _2: number): void;
  ___cxa_uncaught_exceptions(): number;
  ___cxa_current_primary_exception(): number;
  __ZSt9terminatev(): void;
  ___cxa_rethrow_primary_exception(_0: number): void;
  __ZNKSt13runtime_error4whatEv(_0: number): number;
  __ZNSt11logic_errorD2Ev(_0: number): number;
  __ZNKSt11logic_error4whatEv(_0: number): number;
  __ZSt15get_new_handlerv(): number;
  __ZdaPvm(_0: number, _1: number): void;
  __ZdlPvSt11align_val_t(_0: number, _1: number): void;
  __ZdaPvmSt11align_val_t(_0: number, _1: number, _2: number): void;
  ___dynamic_cast(_0: number, _1: number, _2: number, _3: number): number;
  __ZNSt13runtime_errorD2Ev(_0: number): number;
  ___cxa_bad_cast(): void;
  ___cxa_bad_typeid(): void;
  ___cxa_throw_bad_array_new_length(): void;
  __ZSt14set_unexpectedPFvvE(_0: number): number;
  __ZSt13set_terminatePFvvE(_0: number): number;
  __ZSt15set_new_handlerPFvvE(_0: number): number;
  ___cxa_guard_acquire(_0: number): number;
  ___cxa_guard_release(_0: number): void;
  ___cxa_guard_abort(_0: number): void;
  __ZSt14get_unexpectedv(): number;
  __ZSt10unexpectedv(): void;
  __ZSt13get_terminatev(): number;
  ___cxa_uncaught_exception(): number;
  ___cxa_free_exception(_0: number): void;
  ___cxa_init_primary_exception(_0: number, _1: number, _2: number): number;
  ___cxa_thread_atexit(_0: number, _1: number, _2: number): number;
  ___cxa_deleted_virtual(): void;
  __ZNSt9type_infoD2Ev(_0: number): number;
  __ZNSt9exceptionD0Ev(_0: number): void;
  __ZNSt9exceptionD1Ev(_0: number): number;
  __ZNKSt9exception4whatEv(_0: number): number;
  __ZNSt13bad_exceptionD0Ev(_0: number): void;
  __ZNSt13bad_exceptionD1Ev(_0: number): number;
  __ZNKSt13bad_exception4whatEv(_0: number): number;
  __ZNSt9bad_allocC2Ev(_0: number): number;
  __ZNSt9bad_allocD0Ev(_0: number): void;
  __ZNKSt9bad_alloc4whatEv(_0: number): number;
  __ZNSt20bad_array_new_lengthC2Ev(_0: number): number;
  __ZNSt20bad_array_new_lengthD0Ev(_0: number): void;
  __ZNKSt20bad_array_new_length4whatEv(_0: number): number;
  __ZNSt13bad_exceptionD2Ev(_0: number): number;
  __ZNSt9bad_allocD2Ev(_0: number): number;
  __ZNSt20bad_array_new_lengthD2Ev(_0: number): number;
  __ZNSt11logic_errorD0Ev(_0: number): void;
  __ZNSt11logic_errorD1Ev(_0: number): number;
  __ZNSt13runtime_errorD0Ev(_0: number): void;
  __ZNSt12domain_errorD0Ev(_0: number): void;
  __ZNSt12domain_errorD1Ev(_0: number): number;
  __ZNSt16invalid_argumentD0Ev(_0: number): void;
  __ZNSt12length_errorD0Ev(_0: number): void;
  __ZNSt12out_of_rangeD0Ev(_0: number): void;
  __ZNSt11range_errorD0Ev(_0: number): void;
  __ZNSt11range_errorD1Ev(_0: number): number;
  __ZNSt14overflow_errorD0Ev(_0: number): void;
  __ZNSt14overflow_errorD1Ev(_0: number): number;
  __ZNSt15underflow_errorD0Ev(_0: number): void;
  __ZNSt15underflow_errorD1Ev(_0: number): number;
  __ZNSt12domain_errorD2Ev(_0: number): number;
  __ZNSt16invalid_argumentD2Ev(_0: number): number;
  __ZNSt12length_errorD2Ev(_0: number): number;
  __ZNSt12out_of_rangeD2Ev(_0: number): number;
  __ZNSt11range_errorD2Ev(_0: number): number;
  __ZNSt14overflow_errorD2Ev(_0: number): number;
  __ZNSt15underflow_errorD2Ev(_0: number): number;
  __ZNSt9type_infoD0Ev(_0: number): void;
  __ZNSt9type_infoD1Ev(_0: number): number;
  __ZNSt8bad_castC2Ev(_0: number): number;
  __ZNSt8bad_castD0Ev(_0: number): void;
  __ZNSt8bad_castD1Ev(_0: number): number;
  __ZNKSt8bad_cast4whatEv(_0: number): number;
  __ZNSt10bad_typeidC2Ev(_0: number): number;
  __ZNSt10bad_typeidD2Ev(_0: number): number;
  __ZNSt10bad_typeidD0Ev(_0: number): void;
  __ZNSt10bad_typeidD1Ev(_0: number): number;
  __ZNKSt10bad_typeid4whatEv(_0: number): number;
  __ZNSt8bad_castC1Ev(_0: number): number;
  __ZNSt10bad_typeidC1Ev(_0: number): number;
}

export interface ClassHandle {
  isAliasOf(other: ClassHandle): boolean;
  delete(): void;
  deleteLater(): this;
  isDeleted(): boolean;
  clone(): this;
}
export interface VectorUint8 extends ClassHandle {
  push_back(_0: number): void;
  resize(_0: number, _1: number): void;
  size(): number;
  get(_0: number): number | undefined;
  set(_0: number, _1: number): boolean;
}

interface EmbindModule {
  VectorUint8: {
    new(): VectorUint8;
  };
  test(): void;
  cleanupGraph(): void;
  initRandomGraph(): any;
  what_to_stderr(_0: number): any;
  dijkstra_source_to_target(_0: number, _1: number): any;
  dijkstra_source_to_all(_0: number): any;
  yen_source_to_target(_0: number, _1: number, _2: number): any;
  bellman_ford_source_to_target(_0: number, _1: number): any;
  bellman_ford_source_to_all(_0: number): any;
  bfs(_0: number): any;
  dfs(_0: number): any;
  random_walk(_0: number, _1: number): any;
  min_spanning_tree(): any;
  betweenness_centrality(): any;
  closeness_centrality(): any;
  degree_centrality(): any;
  eigenvector_centrality(): any;
  strength_centrality(): any;
  harmonic_centrality(): any;
  pagerank(_0: number): any;
  louvain(_0: number): any;
  leiden(_0: number): any;
  fast_greedy(): any;
  label_propagation(): any;
  local_clustering_coefficient(): any;
  k_core(_0: number): any;
  triangle_count(): any;
  strongly_connected_components(): any;
  weakly_connected_components(): any;
  vertices_are_adjacent(_0: number, _1: number): any;
  jaccard_similarity(_0: any): any;
  topological_sort(): any;
  diameter(): any;
  eulerian_path(): any;
  eulerian_circuit(): any;
  missing_edge_prediction_default_values(): any;
  missing_edge_prediction(_0: number, _1: number): any;
  create_graph_from_kuzu_to_igraph(_0: number, _1: any, _2: any, _3: boolean, _4: any): void;
}

export type MainModule = WasmModule & typeof RuntimeExports & EmbindModule;
export default function MainModuleFactory (options?: unknown): Promise<MainModule>;
